#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'game_shader_dx9'

def options(opt):
	# stub
	return

def configure(conf):
	conf.env.append_unique('DEFINES',[
		'STDSHADER_DX9_DLL_EXPORT',
		'FAST_MATERIALVAR_ACCESS',
		'PARALLAX_CORRECTED_CUBEMAPS',
		'GAME_SHADER_DLL',
		'PROCSHADER_DLL',
		'SHADER_EDITOR_DLL',
		'SHADER_EDITOR_DLL_2013',
	])

	game = conf.options.GAMES
	conf.env.GAMES = game

def build(bld):
	source = [
		'basevsshader.cpp',
		'nodeshader.cpp',
		'procshader.cpp',
		'prev.cpp',
		'../ivprocshader.cpp',
		'../procshaderinterface.cpp',
	]

	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'fxctmp9',
		'fxctmp9_tmp',
		'vshtmp9',
		'procshader',
	] + bld.env.INCLUDES_SDL2

	defines = []

	libs = ['tier0','shaderlib','tier1','mathlib', 'vstdlib']

	if bld.env.DEST_OS == 'android':
		libs += ['ANDROID_SUPPORT']

	install_path = bld.env.PREFIX
	if bld.env.DEST_OS != 'android':
		install_path += '/'+bld.env.GAMES+'/bin'

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

