#!/bin/bash
if [ "$#" -ne 3 ]; then
	echo "Usage: $0 <directory> <string for find> <string for replace>"
	exit 1
fi

directory="$1"
search_string="$2"
replace_string="$3"

find "$directory" -type f -exec sed -i "s|$search_string|$replace_string|g" {} \;

echo "Done!"
