name: android-build

on: [push, pull_request]

jobs:
  build-apk-for-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cloning modlaucher repo and preparing for building
      run: |
        git clone https://github.com/ItzVladik/srceng-mod-launcher
        sudo apt-get update
        sudo apt-get install -f -y openjdk-8-jre zip apksigner imagemagick
    - name: Build Android (32 bit)
      run: |
        scripts/build-android-armv7a.sh
    - name: Build Android (64 bit)
      run: |
        chmod +x scripts/build-android-aarch64.sh
        scripts/build-android-aarch64.sh   
    - name: Build APK
      run: |
        chmod +x scripts/build-apk.sh
        scripts/build-apk.sh
    - name: Rename APK
      run: |
         mv srceng-mod-launcher/build/android/mod-signed.apk mod-release.apk

 
    - name: Upload a Build Artifact
  uses: actions/upload-artifact@v4.6.2
  with:
    # Artifact name
    name: mod # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
    path: mod-test.apk
    # The desired behavior if no files are found using the provided path.
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail

    if-no-files-found: warn
    # Duration after which artifact will expire in days. 0 means using default retention.
Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

    retention-days: 1 # optional
    # The level of compression for Zlib to be applied to the artifact archive. The value can range from 0 to 9: - 0: No compression - 1: Best speed - 6: Default compression (same as GNU Gzip) - 9: Best compression Higher levels will result in better compression, but will take longer to complete. For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.

    compression-level: 6 # optional, default is 6
    # If true, an artifact with a matching name will be deleted before a new one is uploaded. If false, the action will fail if an artifact for the given name already exists. Does not fail if the artifact does not exist.

    overwrite: false # optional, default is false
    # If true, hidden files will be included in the artifact. If false, hidden files will be excluded from the artifact.

    include-hidden-files: false # optional, default is false
          
